name: EnderAuth
main: EnderAuthTeam\EnderAuth\MainClass
version: 0.0.1
api: [2.0.0]
author: EndKingdom
description: The best PocketMine-MP auth plugin.
commands:
 register:
  usage: /register (email) (password)
 login:
  usage: /login (password)
