name: EnderAuth
author: Matthww
main: EnderAuth\EnderAuth\Loader
version: "1.0.0"
api: [1.13.0]
description: EnderAuth authentication plugin
commands:
    login:
        description: Login.
    register:
        description: Register
    changepw:
        description: Change password.
    unregister:
        description: Unregister account.
   
    
